abstract class SocialRegisterStates{}

class SocialRegisterInitialState extends SocialRegisterStates{}
class SocialRegisterLoadingState extends SocialRegisterStates{}
class SocialRegisterErrorState extends SocialRegisterStates{}
class SocialRegisterSuccessState extends SocialRegisterStates{}